Fix TypeError
A call to /schemas/{schema_id}/write_record results in a TypeError exception:

TypeError: inject() got an unexpected keyword argument 'required'